config/routes.rb
Rails.application.routes.draw do
  get 'static/policy'
  get 'homeru/create'
  get 'follow/:screen_name', to: 'follow#create'
  get 'unfollow/:screen_name', to: 'follow#disable'
  get 'status/:screen_name', to: 'users#status'

  get 'resend', to: 'users#lost_mail'
  post 'resend', to: 'users#resend'

  get 'homeru/create/:to/:type', to: 'homeru#create'

  post 'homete/create', to: 'homete#create'
  get 'homete/edit/:id', to: 'homete#edit'
  post 'homete/update/:id', to: 'homete#update'
  get 'homete/destroy/:id', to: 'homete#destroy'
  get 'homete/destroy_ajax/:id', to: 'homete#destroy_ajax'
  get 'homete/search', to: 'homete#search'

  get 'mute/enable/:screen_name', to: 'mute#enable'
  get 'mute/disable/:screen_name', to: 'mute#disable'
  get 'mutes', to: 'mute#mutes_list'
  get 'admin', to: 'admin#top'
  get 'admin/destroy_user/:id', to: 'admin#destroy_user'
  get 'admin/lock/:id', to: 'admin#lock'
  get 'admin/unlock/:id', to: 'admin#unlock'
  get 'admin/all', to: 'admin#all'

  get 'follows', to: 'follow#follows_list'
  get 'followers', to: 'follow#followers_list'
  get 'notifications', to: 'notification#show'

  get 'popular', to: 'homete#popular'
  get 'homete/:id', to: 'homete#show'

  get 'privacy-policy', to: 'static#policy'
  get 'terms', to: 'static#terms'
  get 'help', to: 'static#help'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
     registrations: 'users/registrations',
     sessions: 'users/sessions',
     omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hometes = []
    if current_user then
      #recommended_hometes = get_recommend_hometes(100)
      recommended_hometes = []
      @follow = Follow.where(from: current_user.id, enable: true).pluck(:to)
      @follow.append(current_user.id)
      @follower = Follow.where(to: current_user.id)

      if rand(0...10) == 0 || \
        current_user.homeru_count == 0 || !current_user.homeru_count || \
        current_user.homerare_count == 0 || !current_user.homerare_count then
        @homerus = Homeru.where(author: current_user.id)
        homerare_count = 0
        homerares = Homete.where(author: current_user.id)
        homerares.each do |homerare|
          h = Homeru.where(to: homerare.id)
          homerare_count += h.count
        end
        current_user.update(homeru_count: @homerus.count, homerare_count: homerare_count)
      end
      
      recommend_ids = []
      recommended_hometes.each do |homete|
        recommend_ids.append(homete.id)
      end
      
      @pages = false
      if params[:page] then
        @pages = true
      end

      # おすすめほめてが50より少なかったら、最新の投稿も対象に入れる
      if recommend_ids.count < 50 then
        recent_homete_ids = Homete.all.order(id: "DESC").limit(50).pluck(:id)
        @hometes = Homete.order(id: "DESC").where(:author => @follow).\
        or(Homete.where(:id => recommend_ids)).\
        or(Homete.where(:id => recent_homete_ids)).\
        page(params[:page]).per(ENV['HOMETES_PER_ONE_PAGE'].to_i)
      else 
        # おすすめほめてが十分にあれば、フォローしている人と、おすすめほめてだけをTLの対象
        @hometes = Homete.order(id: "DESC").where(:author => @follow).\
        or(Homete.where(:id => recommend_ids)).\
        page(params[:page]).per(ENV['HOMETES_PER_ONE_PAGE'].to_i)
      end

      @homeru_count = current_user.homeru_count
      @homerare_count = current_user.homerare_count
    else
      @hometes = get_recommend_hometes(30)
    end
  end

  private
  def get_recommend_hometes(count)
    recommended_hometes = []
    from = Time.now - ENV['RECOMMEND_HOMETE_LIMIT'].to_i.hour
    to = Time.now
    recent_homerus = Homeru.where(created_at: from..to).pluck(:author)
    most_homeru_users = recent_homerus.group_by(&:itself).transform_values(&:size)
    most_homeru_users = most_homeru_users.sort_by { |_, v| -v }.to_h

    total = 0
    ref_val = {}
    target_users = {}
    most_homeru_users.each do |id, val|
      if Homete.where(author: id).count == 0
        next
      end
      # フォローしている人は除外する
      if current_user then
        if Follow.find_by(from: current_user.id, to: id, enable: true) then
          next
        end
      end
      if id == 0 then
        next
      end
      total += val
      ref_val[id] = total
      target_users[id] = 0
    end

    for i in 1..count do
      r = rand(total)
      ref_val.each do |id, val|
        if val > r then
          target_users[id] += 1
          break
        end
      end
    end

    target_users.each do |id, count|
      user = User.find_by(id: id)
      hometes = Homete.order(id: "DESC").where(author: user.id).limit(count)
      recommended_hometes += hometes
    end

    recommended_hometes = recommended_hometes.sort_by{|x| x.created_at}.reverse
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def convert_tag(str)
    str = str.gsub("<","&lt;")
    str = str.gsub(">","&gt;")
    str = str.gsub("\n","<br>")
    Rinku.auto_link(str, :all, 'target="_blank"')
  end

  def omit_content(str, id)
    if str.length > ENV['NOT_OMITTED_LIMIT'].to_i then
      str.slice!(ENV['NOT_OMITTED_LIMIT'].to_i, str.length)
      str += "<br /><br /><a href=\"/homete/#{id}\">続きを読む</a>"
    end
    str
  end

  def showIcon(target_user, size=50)
    if target_user.icon_image.to_s.include?(".png") or target_user.icon_image.to_s.include?(".jpg") \
      or target_user.icon_image.to_s.include?(".jpeg") or target_user.icon_image.to_s.include?(".gif") then
      "<img src=\"#{target_user.icon_image}\" width=\"#{size}px\" height=\"#{size}px\">".html_safe
    else
      "<img src=\"/uploads/default_icon.png\" width=\"#{size}px\" height=\"#{size}px\">".html_safe
    end
  end

  def showHomeruCount(to, type)
    if type == 0 then #all
      homerus = Homeru.where(to: to)
    else
      homerus = Homeru.where(to: to, hometype: type)
    end
    "#{homerus.count}"
  end
end

app/views/home/index.html.erb
<% if user_signed_in? %>
    <% if @pages then %>
        <%= link_to 'javascript:void(0);', style: "display: inline-block;" ,onclick: "showPostBox()".html_safe, id: "show_post_box" do %>
            <i class="fas fa-plus-circle"></i>投稿する
        <% end %>
        <%= link_to 'javascript:void(0);', style: "display: none;" , onclick: "hidePostBox()".html_safe, id: "hide_post_box" do %>
            <i class="fas fa-window-close"></i>
        <% end %>
        <div id="post_box" style="display:none;">
    <% else %>
        <div id="post_box" style="display:block;">
    <% end %>
    <div class="show-icon">
        <table>
            <tr>
                <td>
                    <%= link_to("/status/#{current_user.screen_name}") do %>
                        <%= showIcon(current_user) %>
                    <% end %>
                </td>
                <td>
                    <%= link_to("/status/#{current_user.screen_name}") do %>
                        <%= current_user.name %><br />
                        @<%= current_user.screen_name %>
                    <% end %>
                </td>
            </tr>
        </table>
    </div>
    <div class="show-follow">
        <%= link_to "フォロー", follows_path, :method=> :get %><%= @follow.count-1 %> /
        <%= link_to "フォロワー", followers_path, :method=> :get %><%= @follower.count %>
    </div>
    <div class="show-homete">
        <%= @homeru_count %>ほめた /
        <%= @homerare_count %>ほめられた
    </div>
    <hr>
    <%= form_tag(homete_create_path, method: :post, multipart: true) do %>
        <%= text_area_tag :content, nil, class: "content", :placeholder => "ほめてほしいことを書いてください" %><br />
        <%= file_field_tag 'images[]', class: "upload-image", multiple: true %><br />
        <span class="mini-desc">※画像を最大5枚までアップロードできます。</span><br />
        <%= submit_tag "ほめて!", id: "homete" %>
    <% end %>
    </div>
    <hr>
    <%= render "users/shared/show_homete", :hometes => @hometes %>
    <%= paginate @hometes %>
<% else %>
    <div class="guidance-area">
        <%= image_tag "/guidance.png", :class => "guidance" %><br />
        <span class="mini-desc">※公序良俗に反する書き込みをするユーザーは、管理者の判断で削除させていただきます。</span><br />
        <span class="mini-desc">※18歳未満または未成年者に禁止されているコンテンツを直接貼り付けることは禁止です（間接はOK）。</span>
    </div>
    <hr>
    <%= link_to new_user_registration_path, :method => :get do %>
        <div class="arrow-button">新規登録
        <i class="fas fa-arrow-right"></i></div>
    <% end %>
    <%= link_to new_user_session_path, :method => :get do %>
        <div class="arrow-button">ログイン
        <i class="fas fa-arrow-right"></i></div>
    <% end %>
    <div>
        Twitter API の有料化に伴い Twitter アカウントでのログインを廃止しました。<br />
        パスワードを設定していない方は、「ログイン」→「パスワードを忘れた」からパスワードの再設定を行ってください。
    </div>
    <script type="text/javascript">
    var nend_params = {"media":68211,"site":352607,"spot":1046363,"type":10,"oriented":1};
    </script>
    <hr>
    <h3>人気のほめて</h3>
    <%= render "users/shared/show_homete", :hometes => @hometes, :pushed_table => @pushed_table %>
<% end %>